### ISSUE TITLE
Element highlighting causes BulletChart DataPoint and Legend color read failures

### ISSUE THREAD

**Issue by mshriver** [RedHatQE/widgetastic.patternfly4#158]
When element highlighting is enabled, the `DataPoint.color` and `Legend.color` can end up reading `rgb(0, 0, 0)`. This is due to the highlighting DOM change making pie elements go black in color instead of display a red border.

This causes unit test failures, and will impact users of the element highlighting feature in general.

I would propose making the `Legend` class implement  properties for label, value, and color, which will use the `element` instance attribute to make a lazy lookup.  

A potential change to the `Legend` class that would make sense to do concurrently would be convert to a `Widget` class and use a ParametrizedLocator instead of passing the element from BulletChart on instantiation. 

See #159 as a recreation.

**Comment by digitronik** [comment]
It fixed. please reopen it if needed.
