### ISSUE TITLE
RFE ability of Select to account for menuAppendTo={() => document.body}

### ISSUE THREAD

**Issue by pondrejk** [RedHatQE/widgetastic.patternfly4#171]
Encountered in Satellite ui, if select uses menuAppendTo={() => document.body}, widgetastic can not find list members, see https://bugzilla.redhat.com/show_bug.cgi?id=2182353

**Comment by LightOfHeaven1994** [comment]
@pondrejk I took a look on this issue. In this case we couldn't do anything as menu element could be append to other elements that we couldn't predict. For example, [here I see `menuAppendTo` was removed from multiple places ](https://github.com/theforeman/foreman_remote_execution/pull/795/files) . In one of the cases it was appended to `document.querySelector('.pf-c-form.schedule-tab')}`. 

In your situation, you could import Select widget and customize it on your side. Example:

```
from widgetastic_patternfly4 import Select

class MyCustomSelect(Select):
    ITEMS_LOCATOR = ".//ul/li....."
    
    def item_select(....):
        # overwrite method
```

I hope it helps
