### ISSUE TITLE
Support for Grid?

### ISSUE THREAD

**Issue by catastrophe-brandon** [RedHatQE/widgetastic.patternfly4#185]
After grepping the codebase, I didn't see any mention of [Grid](https://www.patternfly.org/v4/layouts/grid/html/). Does any support for this exist?

**Comment by digitronik** [comment]
@catastrophe-brandon looks like its layout and it's more generic. 
I think for such implementation we mostly use views but still if you point out any use case that will be helpful.

**Comment by catastrophe-brandon** [comment]
For now I'll focus on using View until I find a situation where it won't work ;)
